[phases]
    setup = [
      "nodejs-18_x",
      "npm"
    ]
    install = "npm install --omit=dev --no-audit --no-fund --prefer-offline"
    build = "npm run build"
    start = "npm run start"
    
    [config]
    node_version = "18"
    npm_version = "9"
    max_install_time = 1800
    max_build_time = 1800
